name: parcom ci

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'

jobs:
  test:
    name: Build, Test and Check coverage
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install kcov
        run: |
          sudo apt-get update 
          sudo apt-get install -y kcov

      - name: Install zig
        uses: mlugg/setup-zig@v2

      - name: Zig build test
        run: zig build test -Dtest-coverage --summary all

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          fail_ci_if_error: true
