name: parcom ci

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
      - run: zig build test --summary all
